import Head from "next/head";
import Button from "../components/Button";
import Features from "../sections/features";
import Hero from "../components/Hero";
import Slider from "../sections/slider";
import TopNav from "../components/TopNav";
import Navigation from "../components/Navigation";
import Intro from "../components/Intro";
import Footer from "../components/Footer";
import BottomNav from "../components/BottomNav";

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-grow">
        <TopNav />
        <Navigation />
        <Hero />
        <Intro />
        <Slider />
        <Footer />
        <BottomNav />
      </main>
      <footer></footer>
    </div>
  );
}
