import Head from "next/head";
import Button from "../components/Button";
import Features from "../sections/features";
import Hero from "../sections/heros";
import Slider from "../sections/slider";

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-grow">
        <Button>Ola</Button>
        <div className="relative h-0 max-w-6xl pointer-events-none z-[-1]">
          <svg
            className="absolute -mr-16 top-0 right-0 transform translate-x-1/2"
            width="800"
            height="502"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <circle
              cx="400"
              cy="102"
              r="400"
              fill="url(#heroglow_paint0_radial)"
              fillOpacity=".6"
            ></circle>
            <circle
              cx="209"
              cy="289"
              r="170"
              fill="url(#heroglow_paint1_radial)"
              fillOpacity=".4"
            ></circle>
            <defs>
              <radialGradient
                id="heroglow_paint0_radial"
                cx="0"
                cy="0"
                r="1"
                gradientUnits="userSpaceOnUse"
                gradientTransform="rotate(90 149 251) scale(315.089)"
              >
                <stop stopColor="#3ABAB4"></stop>
                <stop offset="1" stopColor="#3ABAB4" stopOpacity=".01"></stop>
              </radialGradient>
              <radialGradient
                id="heroglow_paint1_radial"
                cx="0"
                cy="0"
                r="1"
                gradientUnits="userSpaceOnUse"
                gradientTransform="rotate(90 -40 249) scale(133.913)"
              >
                <stop stopColor="#667EEA"></stop>
                <stop offset="1" stopColor="#667EEA" stopOpacity=".01"></stop>
              </radialGradient>
            </defs>
          </svg>
        </div>
        <Hero />
        <Features />
        <Slider />
      </main>
      <footer></footer>
    </div>
  );
}
