import Head from "next/head";
import Button from "../components/Button";
import Features from "../sections/features";
import Hero from "../components/Hero";
import Slider from "../sections/slider";
import TopNav from "../components/TopNav";
import Navigation from "../components/Navigation";

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-grow">
        <TopNav />
        <Navigation />
        <Hero />
      </main>
      <footer></footer>
    </div>
  );
}
