import { useEffect } from "react";

import Head from "next/head";
import Hero from "../components/Hero";
import Slider from "../sections/slider";
import TopNav from "../components/TopNav";
import Navigation from "../components/Navigation";
import Intro from "../components/Intro";
import Footer from "../components/Footer";
import BottomNav from "../components/BottomNav";
import Enquiry from "../components/Enquiry";

import AOS from "aos";
import "aos/dist/aos.css";
import Events from "../components/Events";

export default function Home() {
  useEffect(() => {
    AOS.init({ once: true });
  }, []);

  return (
    <div className="flex flex-col min-h-screen overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-grow">
        <TopNav />
        <Navigation />
        <Hero />
        <Intro />
        <Slider />
        <Events />
        <Enquiry />
      </main>
      <Footer />
      <BottomNav />
    </div>
  );
}
